# Generated by Django 2.2.7 on 2020-03-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_province', models.CharField(default='', max_length=255)),
                ('country_region', models.CharField(default='', max_length=255)),
                ('latitude', models.CharField(default=0, max_length=255)),
                ('longitude', models.CharField(default=0, max_length=255)),
                ('stats_type', models.CharField(default='', max_length=255)),
                ('stats_dates_csv', models.TextField(default='')),
                ('stats_value_csv', models.TextField(default='')),
                ('latest_stats_date', models.CharField(default='', max_length=255)),
                ('latest_stats_value', models.CharField(default='', max_length=255)),
                ('added_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
