# Generated by Django 2.2.7 on 2020-03-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='latest_stats_value',
            field=models.IntegerField(),
        ),
    ]
