# Generated by Django 2.2.7 on 2020-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200315_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_ts', models.DateTimeField(auto_now_add=True)),
                ('json_string', models.TextField(default='')),
            ],
        ),
    ]
