# Generated by Django 2.2.7 on 2020-03-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='latest_stats_value',
            field=models.IntegerField(default=0),
        ),
    ]
