# Generated by Django 3.0.4 on 2020-03-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dump',
        ),
    ]
