# Generated by Django 3.0.4 on 2020-04-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_record_country_alpha3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='country_alpha3',
            new_name='country_alpha32',
        ),
    ]
