# Generated by Django 3.0.4 on 2020-04-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200403_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='country_alpha32',
            new_name='country_alpha3',
        ),
    ]
